### ISSUE TITLE
ISSUE-14611: when i use pulsar in k8s, how to set advertisedListeners in broker.conf for different broker pods  , 

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#3882]
Original Issue: apache/pulsar#14611 

---

how to set advertisedListeners in broker.conf for different broker pods  , when i use pulsar in k8s，such as：
```
pulsar-cluster-broker-0
pulsar-cluster-broker-1
pulsar-cluster-broker-2
```

and broker.conf  for pod:  pulsar-cluster-broker-0
```
advertisedListeners=internal:pulsar://pulsar-cluster-broker-0.pulsar-cluster-broker.pulsar.svc.cluster.local:6650,external:pulsar://x.x.x.x34000
```

for pulsar-cluster-broker-1
```
advertisedListeners=internal:pulsar://pulsar-cluster-broker-1.pulsar-cluster-broker.pulsar.svc.cluster.local:6650,external:pulsar://x.x.x.x34000
```

in pulsar-broker ConfigMap value:
```
advertisedListeners: ""
```

and i can get POD_NAME in env.
```
 env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name 
```
how to use  bin/apply-config-from-env.py conf/bookkeeper.conf to set advertisedListeners in broker.conf,  Assign different values with env:  POD_NAME
